### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by informusica** [pat-alt/CounterfactualExplanations.jl#25]
note that some symbols (underlined x and y) render as x̲  and y̲ in the browser. I am e.g. noticing this in
https://github.com/pat-alt/CounterfactualExplanations.jl/blob/b58006ca4b69069aeee4fddaa2d5c5773b2c25db/docs/src/intro.qmd#L52

and

https://github.com/pat-alt/CounterfactualExplanations.jl/blob/b58006ca4b69069aeee4fddaa2d5c5773b2c25db/docs/src/tutorials/binary.md?plain=1#L25

**Comment by informusica** [comment]
I also think there either is a superfluous '\' or a missing LaTeX encoding in

https://github.com/pat-alt/CounterfactualExplanations.jl/blob/b58006ca4b69069aeee4fddaa2d5c5773b2c25db/docs/src/cats_dogs.md?plain=1#L39

(now rendering as \> 75%)

**Comment by pat-alt** [comment]
Thanks, both fixed in #29
